(defun play-RSP (pick1 pick2)
  (or (and (equal pick1 pick2) 'tie)
      (and (and (equal pick1 'rock) (equal pick2 'scissors)) 'first-wins)
      (and (and (equal pick1 'scissors) (equal pick2 'paper)) 'first-wins)
      (and (and (equal pick1 'paper) (equal pick2 'rock)) 'first-wins)
      'second-wins))

(format t "~s = ~s~%" '(play-RSP 'rock 'rock) (play-RSP 'rock 'rock))
(format t "~s = ~s~%" '(play-RSP 'rock 'scissors) (play-RSP 'rock 'scissors))
(format t "~s = ~s~%" '(play-RSP 'rock 'paper) (play-RSP 'rock 'paper))
(format t "~s = ~s~%" '(play-RSP 'scissors 'rock) (play-RSP 'scissors 'rock))
(format t "~s = ~s~%" '(play-RSP 'scissors 'scissors) (play-RSP 'scissors 'scissors))
(format t "~s = ~s~%" '(play-RSP 'scissors 'paper) (play-RSP 'scissors 'paper))
(format t "~s = ~s~%" '(play-RSP 'paper 'rock) (play-RSP 'paper 'rock))
(format t "~s = ~s~%" '(play-RSP 'paper 'scissors) (play-RSP 'paper 'scissors))
(format t "~s = ~s~%" '(play-RSP 'paper 'paper) (play-RSP 'paper 'paper))
