(defun space-over (n)
  (cond ((zerop n) nil)
        ((not (plusp n)) (format t "Error!"))
        (t (format t " ")(space-over (- n 1)))))

(defun test-space-over (n)
  (format t "~%>>>")
  (space-over n)
  (format t "<<<"))

(defun plot-one-point (str col)
  (format t "~%")
  (space-over col)
  (format t "~A~%" str))

(defun plot-points (str listy)
  (cond ((null listy) nil)
        (t (plot-one-point str (first listy))
           (plot-points str (rest listy)))))

(defun generate (m n)
  (cond ((> m n) nil)
        (t (cons m (generate (+ m 1) n)))))

(defun make-graph ()
  (labels ((prompt-and-get-value (prompt)
                                 (format t "~&~A" prompt)
                                 (read)))
    (let ((func (prompt-and-get-value "Function to plot: "))
          (start-x (prompt-and-get-value "Starting x-value: "))
          (end-x (prompt-and-get-value "Ending x-value: "))
          (plot-str (prompt-and-get-value "Plotting string: ")))
      (plot-points plot-str (mapcar func (generate start-x end-x))))))

(defun square (n)
  (* n n))

;(dribble "9.10.out.txt")
(let ((parta1 '(test-space-over 5))
      (parta2 '(test-space-over -5))
      (partb1 '(plot-one-point "*" 5))
      (partc1 '(plot-points "<>" '(4 6 8 10 8 6 4)))
      (partd1 '(generate -3 3))
      (partf1 '(make-graph)))
  (format t "~&Testing ~s:" parta1)
  (eval parta1)
  (format t "~&Testing ~s:" parta2)
  (eval parta2)
  (format t "~&Testing ~s:" partb1)
  (eval partb1)
  (format t "~&Testing ~s:" partc1)
  (eval partc1)
  (format t "~&~s = ~s" partd1 (eval partd1))
  (format t "~&Testing ~s:" partf1)
  (eval partf1))
;(dribble)
