(defun hybrid-prin1 (x)
  (declare (notinline (hybrid-prin1)))
  (labels ((hybrib-prin-cdr (x)
                            (cond ((null x)
                                   (format t ")"))
                                  ((atom x)
                                   (format t " . ~s)" x))
                                  (t
                                    (format t " ")
                                    (hybrid-prin1 (car x))
                                    (hybrib-prin-cdr (cdr x))))))
    (cond ((atom x)
           (format t "~s" x))
          (t (format t "(")
             (hybrid-prin1 (first x))
             (hybrib-prin-cdr (rest x))))))

(let ((test1 '(hybrid-prin1 '(a)))
      (test2 '(hybrid-prin1 '(a b)))
      (test3 '(hybrid-prin1 '(a . b)))
      (test4 '(hybrid-prin1 '(a b . c)))
      (test5 '(hybrid-prin1 '(a b c . d)))
      (test6 '(hybrid-prin1 '((a) b c . d))))
  (format t "~&Testing ~s~%" test1)
  (eval test1)
  (format t "~&Testing ~s~%" test2)
  (eval test2)
  (format t "~&Testing ~s~%" test3)
  (eval test3)
  (format t "~&Testing ~s~%" test4)
  (eval test4)
  (format t "~&Testing ~s~%" test5)
  (eval test5)
  (format t "~&Testing ~s~%" test6)
  (eval test6))
