(defun find-largest (list-of-numbers)
  (do* ((largest (first list-of-numbers))
        (rest-list list-of-numbers (rest rest-list))
        (element largest (first rest-list)))
    ((null rest-list) largest)
    (when (> element largest)
      (setf largest element))))

(let ((test1 '(find-largest '(5 10 15 1 2 7 13)))
      (test2 '(find-largest '(1 3 5 7 9 11 13)))
      (test3 '(find-largest '(13 11 9 7 5 3 1)))
      (test4 '(find-largest '())))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4)))
