(defun first-non-integer (x)
  (dolist (e x 'none)
    (unless (integerp e)
      (return e))))

(let ((test1 '(first-non-integer '(1 2 3 4 5)))
      (test2 '(first-non-integer '(1 2 3 foo 5)))
      (test3 '(first-non-integer '(1 2 3 4 foo)))
      (test4 '(first-non-integer '(foo 2 3 4 5)))
      (test5 '(first-non-integer '()))
      (test6 '(first-non-integer '(1 2 3 foo 5 bar 7))))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4))
  (format t "~&~s = ~s" test5 (eval test5))
  (format t "~&~s = ~s" test6 (eval test6)))
