(defun fib (n)
  (do* ((cnt 1 (incf cnt))
        (fibn 1 fibn1)
        (fibn1 1 fibn2)
        (fibn2 2 (+ fibn fibn1)))
    ((>= cnt n) fibn)))

(let ((test1 '(fib 0))
      (test2 '(fib 1))
      (test3 '(fib 2))
      (test4 '(fib 3))
      (test5 '(fib 8)))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4))
  (format t "~&~s = ~s" test5 (eval test5)))
