(defun it-nth (n x)
  (let ((head x))
    (dotimes (i n (first head))
      (setf head (rest head)))))

(let ((test1 '(it-nth 0 '(1 2 3 4 5 6)))
      (test2 '(it-nth 1 '(1 2 3 4 5 6)))
      (test3 '(it-nth 5 '(1 2 3 4 5 6)))
      (test4 '(it-nth 6 '(1 2 3 4 5 6)))
      (test5 '(it-nth 7 '(1 2 3 4 5 6)))
      (test6 '(it-nth 0 '()))
      (test7 '(it-nth 1 '())))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4))
  (format t "~&~s = ~s" test5 (eval test5))
  (format t "~&~s = ~s" test6 (eval test6))
  (format t "~&~s = ~s" test7 (eval test7)))
