(defun it-intersection (set1 set2)
  (let ((result '(1)))
    (dolist (e set1 result)
      (when (member e set2)
        (nconc result (list e))))))

(let ((test1 '(it-intersection '(f a c e) '(c l o v e r)))
      (test2 '(it-intersection '(f a c e) '(1 2 3 4)))
      (test3 '(it-intersection '(f a c e) '(f a c e)))
      (test4 '(it-intersection '(f a c e) '()))
      (test5 '(it-intersection '() '(f a c e)))
      (test6 '(it-intersection '() '())))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4))
  (format t "~&~s = ~s" test5 (eval test5))
  (format t "~&~s = ~s" test6 (eval test6)))
