(defun check-all-odd (x)
  (do ((rest-x x (rest rest-x)))
    ((null rest-x) t)
    (format t "~&Checking ~s..." (first rest-x))
    (when (not (oddp (first rest-x)))
      (return nil))))

(let ((test1 '(check-all-odd '(1 3 5 7)))
      (test2 '(check-all-odd '(1 3 5 6 7)))
      (test3 '(check-all-odd '(2 4 6 8)))
      (test4 '(check-all-odd '())))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4)))
