(defun find-first-odd (x)
  (format t "~&Searching for an odd number...")
  (dolist (element x)
    (when (oddp element)
      (format t "~&Found ~S." element)
      (return-from find-first-odd element)))
  (format t "~&None found.")
  'none)

(let ((test1 '(find-first-odd '(2 4 6 7 8)))
      (test2 '(find-first-odd '(2 4 6 8 10))))
  (format t "~&~s = ~s~%~%" test1 (eval test1))
  (format t "~&~s = ~s~%~%" test2 (eval test2)))

(defun find-first-odd (x)
  (format t "~&Searching for an odd number...")
  (dolist (element x)
    (when (oddp element)
      (format t "~&Found ~S." element)
      (return element)))
  (format t "~&None found.")
  'none)

(let ((test1 '(find-first-odd '(2 4 6 7 8)))
      (test2 '(find-first-odd '(2 4 6 8 10))))
  (format t "~&Testing first-non-integer with return instead of return-from~%~%")
  (format t "~&~s = ~s~%~%" test1 (eval test1))
  (format t "~&~s = ~s~%~%" test2 (eval test2)))
