(defun count-down1 (n)
  (cond ((< n 0) nil)
        (t (cons n (count-down1 (- n 1))))))

(defun count-down2 (n)
  (cond ((>= n 0) (cons n (count-down2 (- n 1))))
        (t nil)))

(let ((test1 '(count-down1 0))
      (test2 '(count-down1 1))
      (test3 '(count-down1 5))
      (test4 '(count-down2 0))
      (test5 '(count-down2 1))
      (test6 '(count-down2 5)))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5))
  (format t "~s = ~s~%" test6 (eval test6)))
