(defun compare-length (x y)
  (cond ((and (null x) (null y)) 'same-length)
        ((and (null x) (not (null y))) 'second-is-longer)
        ((and (not (null x)) (null y)) 'first-is-longer)
        (t (compare-length (rest x) (rest y)))))

(let ((test1 '(compare-length '(a b c d e) '(1 2 3 4 5)))
      (test2 '(compare-length '(a b c d e) '(1 2 3)))
      (test3 '(compare-length '(a b c) '(1 2 3 4 5)))
      (test4 '(compare-length '() '(1 2 3 4 5)))
      (test5 '(compare-length '(a b c d e) '()))
      (test6 '(compare-length '() '())))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5))
  (format t "~s = ~s~%" test6 (eval test6)))
