(defun my-remove (what x)
  (cond ((null x) nil)
        ((equal what (first x))
         (my-remove what (rest x)))
        (t (cons (first x) (my-remove what (rest x))))))

(let ((test1 '(my-remove 'a '(a b c d a f g)))
      (test2 '(my-remove 'd '(a b c d a f g)))
      (test3 '(my-remove 'i '(a b c d a f g)))
      (test4 '(my-remove '() '(a b c d a f g)))
      (test5 '(my-remove 'i '())))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5)))
