(defun my-set-difference (x y)
  (cond ((null x) nil)
        ((not (find (first x) y))
         (cons (first x) (my-set-difference (rest x) y)))
        (t (my-set-difference (rest x) y))))

(let ((test1 '(my-set-difference '(a b c d e f g h i j) '(a e i o u)))
      (test2 '(my-set-difference '(a e i o u) '(a b c d e f g h i j)))
      (test3 '(my-set-difference '(a b c d e f g h i j) '(1 2 3 4 5)))
      (test4 '(my-set-difference '(a b c) '()))
      (test5 '(my-set-difference '() '(a b c)))
      (test6 '(my-set-difference '() '()))
      (test7 '(my-set-difference '(a b c) '(a b c))))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5))
  (format t "~s = ~s~%" test6 (eval test6))
  (format t "~s = ~s~%" test7 (eval test7)))
