(defun merge-lists (x y)
  (let ((first-x (first x))
        (first-y (first y))
        (rest-x (rest x))
        (rest-y (rest y)))
    (cond ((and (null x) (null y)) nil)
          ((null x) y)
          ((null y) x)
          ((<= first-x first-y)
           (cons first-x (merge-lists rest-x y)))
          (t (cons first-y (merge-lists x rest-y))))))

(let ((test1 '(merge-lists '(1 2 6 8 10 12) '(2 3 5 9 13)))
      (test2 '(merge-lists '(2 3 5 9 13) '(1 2 6 8 10 12))))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2)))
