(setf family '((colin nil nil)
               (deirdre nil nil)
               (arthur nil nil)
               (kate nil nil)
               (frank nil nil)
               (linda nil nil)
               (suzanne colin deirdre)
               (bruce arthur kate)
               (charles arthur kate)
               (david arthur kate)
               (ellen arthur kate)
               (george frank linda)
               (hillary frank linda)
               (andre nil nil)
               (tamara bruce suzanne)
               (vincent bruce suzanne)
               (wanda nil nil)
               (ivan george ellen)
               (julie george ellen)
               (marie george ellen)
               (nigel andre hillary)
               (frederick nil tamara)
               (zelda vincent wanda)
               (joshua ivan wanda)
               (quentin nil nil)
               (robert quentin julie)
               (olivia nigel marie)
               (peter nigel marie)
               (erica nil nil)
               (yvette robert zelda)
               (diane peter erica)))

(defun father (name)
  (second (assoc name family)))

(defun mother (name)
  (third (assoc name family)))

(defun parents (name)
  (remove-if #'null (rest (assoc name family))))
;   (remove-if #'null (list (father name) (mother name))))

(defun children (name)
  (and name
       (mapcar
         #'first
         (remove-if-not
           #'(lambda (row) (member name (rest row)))
           family))))

(defun siblings (name)
  (remove name (union (children (father name))
                      (children (mother name)))))

(defun mapunion (func x)
  (reduce #'union (mapcar func x)))

(defun grandparents (name)
  (mapunion #'parents (parents name)))

(defun cousins (name)
  (mapunion #'children (mapunion #'siblings (parents name))))

(defun descended-from (succ pred)
  (let ((both-parents (parents succ))
        (dad (father succ))
        (mom (mother succ)))
    (cond ((null succ) nil)
          ((member pred both-parents) t)
          (t (or (descended-from dad pred)
                 (descended-from mom pred))))))

(defun ancestors (name)
;  (declare (notinline ancestors))
  (let ((both-parents (parents name))
        (dad (father name))
        (mom (mother name)))
    (cond ((null name) nil)
          (t (union both-parents (union (ancestors dad)
                                        (ancestors mom)))))))

(defun generation-gap (person ancestor)
  (let* ((both-parents (parents person))
         (dad (father person))
         (mom (mother person))
         (person-ancestors (ancestors person))
         (dad-ancestors (ancestors dad))
         (mom-ancestors (ancestors mom)))
    (cond ((null person) nil)
          ((not (member ancestor person-ancestors)) nil)
          ((member ancestor both-parents) 1)
          ((and (member ancestor dad-ancestors)
                (member ancestor mom-ancestors))
           (min (+ 1 (generation-gap dad ancestor))
                (+ 1 (generation-gap mom ancestor))))
          ((member ancestor dad-ancestors)
           (+ 1 (generation-gap dad ancestor)))
          (t (+ 1 (generation-gap mom ancestor))))))

(let ((parta1 '(father 'suzanne))
      (parta2 '(mother 'suzanne))
      (parta3 '(parents 'suzanne))
      (parta4 '(parents 'frederick))
      (parta5 '(children 'arthur))
      (partb1 '(siblings 'bruce))
      (partb2 '(siblings 'zelda))
      (partc1 '(mapunion #'rest '((1 a b c)(2 e c j)(3 f a b c d))))
      (partd1 '(grandparents 'suzanne))
      (partd2 '(grandparents 'frederick))
      (partd3 '(grandparents 'yvette))
      (parte1 '(cousins 'julie))
      (partf1 '(descended-from 'tamara 'arthur))
      (partf2 '(descended-from 'tamara 'linda))
      (partg1 '(ancestors 'marie))
      (parth1 '(generation-gap 'suzanne 'colin))
      (parth2 '(generation-gap 'frederick 'colin))
      (parth3 '(generation-gap 'frederick 'linda))
      (parti1 '(descended-from 'robert 'deirdre))
      (parti2 '(ancestors 'yvette))
      (parti3 '(generation-gap 'olivia 'frank))
      (parti4 '(cousins 'peter))
      (parti5 '(grandparents 'olivia)))
  (format t "~s = ~s~%" parta1 (eval parta1))
  (format t "~s = ~s~%" parta2 (eval parta2))
  (format t "~s = ~s~%" parta3 (eval parta3))
  (format t "~s = ~s~%" parta4 (eval parta4))
  (format t "~s = ~s~%" parta5 (eval parta5))
  (format t "~s = ~s~%" partb1 (eval partb1))
  (format t "~s = ~s~%" partb2 (eval partb2))
  (format t "~s = ~s~%" partc1 (eval partc1))
  (format t "~s = ~s~%" partd1 (eval partd1))
  (format t "~s = ~s~%" partd2 (eval partd2))
  (format t "~s = ~s~%" partd3 (eval partd3))
  (format t "~s = ~s~%" parte1 (eval parte1))
  (format t "~s = ~s~%" partf1 (eval partf1))
  (format t "~s = ~s~%" partf2 (eval partf2))
  (format t "~s = ~s~%" partg1 (eval partg1))
  (format t "~s = ~s~%" parth1 (eval parth1))
  (format t "~s = ~s~%" parth2 (eval parth2))
  (format t "~s = ~s~%" parth3 (eval parth3))
  (format t "~s = ~s~%" parti1 (eval parti1))
  (format t "~s = ~s~%" parti2 (eval parti2))
  (format t "~s = ~s~%" parti3 (eval parti3))
  (format t "~s = ~s~%" parti4 (eval parti4))
  (format t "~s = ~s~%" parti5 (eval parti5)))
