(defun legalp (x)
  (cond ((numberp x) t)
        (t (and (or (equal (second x) '+)
                    (equal (second x) '-)
                    (equal (second x) '*)
                    (equal (second x) '/))
                (legalp (first x))
                (legalp (third x))))))

(let ((test1 '(legalp '4))
      (test2 '(legalp '((2 * 2) - 3)))
      (test3 '(legalp '()))
      (test4 '(legalp '(a b c d))))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4)))
