(defun rec-nth (n x)
  (cond ((or (< n 0)
             (null x)) nil)
        ((= n 0) (first x))
        (t (rec-nth (- n 1) (rest x)))))

(let ((test1 '(rec-nth 0 '(a b c d e f g h i)))
      (test2 '(rec-nth 3 '(a b c d e f g h i)))
      (test3 '(rec-nth 8 '(a b c d e f g h i)))
      (test4 '(rec-nth 9 '(a b c d e f g h i)))
      (test5 '(rec-nth 5 '())))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5)))
