(defun my-get (sym prop)
  (do ((p (symbol-plist sym) (rest (rest p))))
    ((null p) nil)
    (when (equal prop (first p))
      (return-from my-get (second p)))))

(defun addprop (sym elem prop)
  (pushnew elem (get sym prop)))
(addprop 'counts 'ek 'one)
(addprop 'counts 1 'one)
(addprop 'counts 'do 'two)
(addprop 'counts 2 'two)
(addprop 'counts 'teen 'three)
(addprop 'counts 3 'three)
(addprop 'counts 'char 'four)
(addprop 'counts 4 'four)

(let ((test1 '(symbol-plist 'counts))
      (test2 '(my-get 'counts 'one))
      (test3 '(my-get 'counts 'two))
      (test4 '(my-get 'counts 'four)))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4)))
