(defun hasprop (sym prop)
  (let ((ret (get sym prop 'hasprop-no-prop)))
    (cond ((equal ret 'hasprop-no-prop)
           nil)
          (t t))))

(defun addprop (sym elem prop)
  (pushnew elem (get sym prop)))
(addprop 'counts 'ek 'one)
(addprop 'counts 1 'one)
(addprop 'counts 'do 'two)
(addprop 'counts 2 'two)
(addprop 'counts nil 'quatre)
(setf (get 'counts 'cinq) nil)

(let ((test1 '(symbol-plist 'counts))
      (test2 '(hasprop 'counts 'one))
      (test3 '(hasprop 'counts 'quatre))
      (test4 '(hasprop 'counts 'cinq))
      (test5 '(hasprop 'counts 'six)))
  (format t "~&~s = ~s" test1 (eval test1))
  (format t "~&~s = ~s" test2 (eval test2))
  (format t "~&~s = ~s" test3 (eval test3))
  (format t "~&~s = ~s" test4 (eval test4))
  (format t "~&~s = ~s" test5 (eval test5)))
