(setf note-table '((c       1)
                   (c-sharp 2)
                   (d       3)
                   (d-sharp 4)
                   (e       5)
                   (f       6)
                   (f-sharp 7)
                   (g       8)
                   (g-sharp 9)
                   (a       10)
                   (a-sharp 11)
                   (b       12)))

(defun numbers (note-list)
  (let ((get-note-rank #'(lambda (note) (second (assoc note note-table)))))
    (mapcar get-note-rank note-list)))

(defun notes (note-ranks)
  (let ((get-note
          #'(lambda (note-rank)
              (car (find-if
                     #'(lambda (entry) (equal note-rank (second entry)))
                     note-table)))))
    (mapcar get-note note-ranks)))

(defun raise (n-keys note-ranks)
  (let ((transpose-note #'(lambda (note-rank) (+ note-rank n-keys))))
    (mapcar transpose-note note-ranks)))

(defun normalize (note-ranks)
  (let ((bring-to-same-octave
          #'(lambda (note-rank) (cond ((> note-rank 12) (- note-rank 12))
                                      ((< note-rank 1) (+ note-rank 12))
                                      (t note-rank)))))
    (mapcar bring-to-same-octave note-ranks)))

(defun transpose (n-steps song)
  (notes (normalize (raise n-steps (numbers song))))) 

(let ((partb1 '(numbers '(e d c d e e e)))
      (partc1 '(notes '(5 3 1 3 5 5 5)))
      (partd1 '(numbers (numbers '(e d c d e e e))))
      (partd2 '(notes (notes '(5 3 1 3 5 5 5))))
      (parte1 '(raise 5 '(5 3 1 3 5 5 5)))
      (partf1 '(raise 5 (numbers '(c e g))))
      (partf2 '(normalize '(6 10 13)))
      (partg1 '(transpose 5 '(e d c d e e e)))
      (partg2 '(transpose 11 '(e d c d e e e)))
      (partg3 '(transpose 12 '(e d c d e e e)))
      (partg4 '(transpose -1 '(e d c d e e e))))
  (format t "~s = ~s~%" partb1 (eval partb1))
  (format t "~s = ~s~%" partc1 (eval partc1))
  (format t "~s = ~s~%" partd1 (eval partd1))
  (format t "~s = ~s~%" partd2 (eval partd2))
  (format t "~s = ~s~%" parte1 (eval parte1))
  (format t "~s = ~s~%" partf1 (eval partf1))
  (format t "~s = ~s~%" partf2 (eval partf2))
  (format t "~s = ~s~%" partg1 (eval partg1))
  (format t "~s = ~s~%" partg2 (eval partg2))
  (format t "~s = ~s~%" partg3 (eval partg3))
  (format t "~s = ~s~%" partg4 (eval partg4)))
