(let* ((produce ''((apple . fruit)
                   (celery . veggie)
                   (banana . fruit)
                   (lettuce . veggie)))
       (part1 (list 'assoc ''banana produce))
       (part2 (list 'rassoc ''fruit produce))
       (part3 (list 'assoc ''lettuce produce))
       (part4 (list 'rassoc ''veggie produce)))
  (format t "~s = ~s~%" part1 (eval part1))
  (format t "~s = ~s~%" part2 (eval part2))
  (format t "~s = ~s~%" part3 (eval part3))
  (format t "~s = ~s~%" part4 (eval part4)))
