(setf atlas '((pennsylvania pittsburgh)
              (new-jersey newark)
              (pennsylvania johnstown)
              (ohio columbus)
              (new-jersey princeton)
              (new-jersey trenton)))
(setf states-atlas '((pennsylvania pittsburgh johnstown)
                     (new-jersey newark)
                     (ohio columbus)
                     (new-jersey princeton trenton)))

(defun cities-in-state (state atlas)
  (rest (assoc state atlas)))

(let ((test1 '(cities-in-state 'pennsylvania atlas))
      (test2 '(cities-in-state 'new-jersey atlas))
      (test3 '(cities-in-state 'pennsylvania states-atlas))
      (test4 '(cities-in-state 'new-jersey states-atlas)))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4)))
