(let* ((set-x1 ())
       (set-y1 ())
       (test1 (list 'set-difference set-x1 set-y1))
       (test2 (list 'set-difference set-y1 set-x1))
       (set-x2 ''(a b c))
       (set-y2 ''(a b c))
       (test3 (list 'set-difference set-x2 set-y2))
       (test4 (list 'set-difference set-y2 set-x2))
       (set-x3 ''(a b d))
       (set-y3 ''(a b e))
       (test5 (list 'set-difference set-x3 set-y3))
       (test6 (list 'set-difference set-y3 set-x3)))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5))
  (format t "~s = ~s~%" test6 (eval test6)))
