(let* ((org-list ''(a b c d))
       (test1 (list 'member ''a org-list))
       (test2 (list 'member ''b org-list))
       (test3 (list 'member ''c org-list))
       (test4 (list 'member ''d org-list))
       (equiv-table ''((a b c d)
                       (b c d)
                       (c d)
                       (d)))
       (test5 (list 'assoc ''a equiv-table))
       (test6 (list 'assoc ''b equiv-table))
       (test7 (list 'assoc ''c equiv-table))
       (test8 (list 'assoc ''d equiv-table)))
  (format t "~s = ~s~%" test1 (eval test1))
  (format t "~s = ~s~%" test2 (eval test2))
  (format t "~s = ~s~%" test3 (eval test3))
  (format t "~s = ~s~%" test4 (eval test4))
  (format t "~s = ~s~%" test5 (eval test5))
  (format t "~s = ~s~%" test6 (eval test6))
  (format t "~s = ~s~%" test7 (eval test7))
  (format t "~s = ~s~%" test8 (eval test8)))
