(setf rooms '((living-room (north front-stairs)
                           (south dining-room)
                           (east kitchen))
              (upstairs-bedroom (west library)
                                (south front-stairs))
              (dining-room (north living-room)
                           (east pantry)
                           (west downstairs-bedroom))
              (kitchen (west living-room)
                       (south pantry))
              (pantry (north kitchen)
                      (west dining-room))
              (downstairs-bedroom (north back-stairs)
                                  (east dining-room))
              (back-stairs (south downstairs-bedroom)
                           (north library))
              (front-stairs (north upstairs-bedroom)
                            (south living-room))
              (library (east upstairs-bedroom)
                       (south back-stairs))))

(defun choices (room-name)
  (rest (assoc room-name rooms)))

(defun look (direction room-name)
  (let ((options (choices room-name)))
    (second (assoc direction options))))

(defun set-robbie-location (place)
  "Moves Robbie to PLACE by setting
  the variable LOC."
  (setf loc place))

(defun how-many-choices ()
  (length (choices loc)))

(defun upstairsp (loc)
  (or (equal loc 'library)
      (equal loc 'upstairs-bedroom)))

(defun onstairsp (loc)
  (or (equal loc 'front-stairs)
      (equal loc 'back-stairs)))

(defun where ()
  (cond ((upstairsp loc) (list 'robbie 'is 'upstairs 'in 'the loc))
        ((onstairsp loc) (list 'robbie 'is 'on 'the loc))
        (t (list 'robbie 'is 'downstairs 'in 'the loc))))

(defun move (where)
  (let ((new-loc (look where loc)))
    (cond ((equal new-loc nil) '(ouch! robbie hit a wall))
          (t (and (set-robbie-location new-loc)
                  (where))))))

(set-robbie-location 'pantry)
(let* ((parta1 '(choices 'pantry))
       (partb1 '(look 'north 'pantry))
       (partb2 '(look 'west 'pantry))
       (partb3 '(look 'south 'pantry))
       (partd1 'loc)
       (partd2 '(how-many-choices))
       (partf1 '(set-robbie-location 'library))
       (partf2 '(where))
       (partf3 '(set-robbie-location 'kitchen))
       (partf4 '(where))
       (partf5 '(set-robbie-location 'front-stairs))
       (partf6 '(where))
       (partg1 '(set-robbie-location 'pantry))
       (partg2 '(move 'south))
       (partg3 '(move 'north))
       (parth1 '(set-robbie-location 'pantry))
       (parth2 '(move 'west))
       (parth3 '(move 'west))
       (parth4 '(move 'north))
       (parth5 '(move 'north))
       (parth6 '(move 'east))
       (parth7 '(move 'south))
       (parth8 '(move 'south))
       (parth9 '(move 'east)))
  (format t "~%~s = ~s~%" parta1 (eval parta1))
  (format t "~s = ~s~%" partb1 (eval partb1))
  (format t "~s = ~s~%" partb2 (eval partb2))
  (format t "~s = ~s~%" partb3 (eval partb3))
  (format t "~s = ~s~%" partd1 (eval partd1))
  (format t "~s = ~s~%" partd2 (eval partd2))
  (format t "~s = ~s~%" partf1 (eval partf1))
  (format t "~s = ~s~%" partf2 (eval partf2))
  (format t "~s = ~s~%" partf3 (eval partf3))
  (format t "~s = ~s~%" partf4 (eval partf4))
  (format t "~s = ~s~%" partf5 (eval partf5))
  (format t "~s = ~s~%" partf6 (eval partf6))
  (format t "~s = ~s~%" partg1 (eval partg1))
  (format t "~s = ~s~%" partg2 (eval partg2))
  (format t "~s = ~s~%" partg3 (eval partg3))
  (format t "~s = ~s~%" parth1 (eval parth1))
  (format t "~s = ~s~%" parth2 (eval parth2))
  (format t "~s = ~s~%" parth3 (eval parth3))
  (format t "~s = ~s~%" parth4 (eval parth4))
  (format t "~s = ~s~%" parth5 (eval parth5))
  (format t "~s = ~s~%" parth6 (eval parth6))
  (format t "~s = ~s~%" parth7 (eval parth7))
  (format t "~s = ~s~%" parth8 (eval parth8))
  (format t "~s = ~s~%" parth9 (eval parth9)))
